/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmstu.devices.manager.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Device service. Represents a row in the &quot;DM_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bmstu.devices.manager.core.model.impl.DeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bmstu.devices.manager.core.model.impl.DeviceImpl}.
 * </p>
 *
 * @author Strahov
 * @see Device
 * @see com.bmstu.devices.manager.core.model.impl.DeviceImpl
 * @see com.bmstu.devices.manager.core.model.impl.DeviceModelImpl
 * @generated
 */
@ProviderType
public interface DeviceModel extends BaseModel<Device>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device model instance should use the {@link Device} interface instead.
	 */

	/**
	 * Returns the primary key of this device.
	 *
	 * @return the primary key of this device
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this device.
	 *
	 * @param primaryKey the primary key of this device
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this device.
	 *
	 * @return the uuid of this device
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this device.
	 *
	 * @param uuid the uuid of this device
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the device ID of this device.
	 *
	 * @return the device ID of this device
	 */
	public long getDeviceId();

	/**
	 * Sets the device ID of this device.
	 *
	 * @param deviceId the device ID of this device
	 */
	public void setDeviceId(long deviceId);

	/**
	 * Returns the group ID of this device.
	 *
	 * @return the group ID of this device
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this device.
	 *
	 * @param groupId the group ID of this device
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this device.
	 *
	 * @return the company ID of this device
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this device.
	 *
	 * @param companyId the company ID of this device
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this device.
	 *
	 * @return the user ID of this device
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this device.
	 *
	 * @param userId the user ID of this device
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this device.
	 *
	 * @return the user uuid of this device
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this device.
	 *
	 * @param userUuid the user uuid of this device
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this device.
	 *
	 * @return the user name of this device
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this device.
	 *
	 * @param userName the user name of this device
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this device.
	 *
	 * @return the create date of this device
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this device.
	 *
	 * @param createDate the create date of this device
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this device.
	 *
	 * @return the modified date of this device
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this device.
	 *
	 * @param modifiedDate the modified date of this device
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this device.
	 *
	 * @return the status of this device
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this device.
	 *
	 * @param status the status of this device
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this device.
	 *
	 * @return the status by user ID of this device
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this device.
	 *
	 * @param statusByUserId the status by user ID of this device
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this device.
	 *
	 * @return the status by user uuid of this device
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this device.
	 *
	 * @param statusByUserUuid the status by user uuid of this device
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this device.
	 *
	 * @return the status by user name of this device
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this device.
	 *
	 * @param statusByUserName the status by user name of this device
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this device.
	 *
	 * @return the status date of this device
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this device.
	 *
	 * @param statusDate the status date of this device
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this device.
	 *
	 * @return the name of this device
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this device.
	 *
	 * @param name the name of this device
	 */
	public void setName(String name);

	/**
	 * Returns the group of this device.
	 *
	 * @return the group of this device
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this device.
	 *
	 * @param group the group of this device
	 */
	public void setGroup(String group);

	/**
	 * Returns the phone number of this device.
	 *
	 * @return the phone number of this device
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this device.
	 *
	 * @param phoneNumber the phone number of this device
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the model of this device.
	 *
	 * @return the model of this device
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this device.
	 *
	 * @param model the model of this device
	 */
	public void setModel(String model);

	/**
	 * Returns the contact of this device.
	 *
	 * @return the contact of this device
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this device.
	 *
	 * @param contact the contact of this device
	 */
	public void setContact(String contact);

	/**
	 * Returns the category of this device.
	 *
	 * @return the category of this device
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this device.
	 *
	 * @param category the category of this device
	 */
	public void setCategory(String category);

	/**
	 * Returns the device attributes of this device.
	 *
	 * @return the device attributes of this device
	 */
	@AutoEscape
	public String getDeviceAttributes();

	/**
	 * Sets the device attributes of this device.
	 *
	 * @param deviceAttributes the device attributes of this device
	 */
	public void setDeviceAttributes(String deviceAttributes);

	/**
	 * Returns the unique ID of this device.
	 *
	 * @return the unique ID of this device
	 */
	@AutoEscape
	public String getUniqueId();

	/**
	 * Sets the unique ID of this device.
	 *
	 * @param uniqueId the unique ID of this device
	 */
	public void setUniqueId(String uniqueId);

	/**
	 * Returns <code>true</code> if this device is approved.
	 *
	 * @return <code>true</code> if this device is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this device is denied.
	 *
	 * @return <code>true</code> if this device is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this device is a draft.
	 *
	 * @return <code>true</code> if this device is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this device is expired.
	 *
	 * @return <code>true</code> if this device is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this device is inactive.
	 *
	 * @return <code>true</code> if this device is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this device is incomplete.
	 *
	 * @return <code>true</code> if this device is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this device is pending.
	 *
	 * @return <code>true</code> if this device is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this device is scheduled.
	 *
	 * @return <code>true</code> if this device is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Device device);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Device> toCacheModel();

	@Override
	public Device toEscapedModel();

	@Override
	public Device toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}